name: "phpdocker"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - PHP_VERSION=${PHP_VERSION:-8.3.9}
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: unless-stopped
    container_name: phpdocker
    volumes:
      - .:/var/www/html
      - ./log:/var/log
    working_dir: /var/www/html
    ports:
      - "${PORTA_APP:-8080}:${PORTA_APP:-8080}"
      - "9003:9003"
    extra_hosts:
      - host.docker.internal:${HOST_IP:-172.17.0.1}
    dns:
      - 1.1.1.1
      - 8.8.8.8