name: "phpdocker"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpdocker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:8000"
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
